### ISSUE TITLE
Getting TypeError in the log on each request

### ISSUE THREAD

**Issue by apirogov** [kennethreitz/flask-sockets#39]
Even when just trying the first example ("simple usage"), I get the following exception on each request:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python3.5/site-packages/gevent/pywsgi.py", line 1253, in handle
    handler.handle()
  File "/usr/lib/python3.5/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/lib/python3.5/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/python3.5/site-packages/gevent/pywsgi.py", line 916, in handle_one_response
    self.log_request()
  File "/home/admin/.local/lib/python3.5/site-packages/geventwebsocket/handler.py", line 236, in log_request
    if '101' not in self.status:
TypeError: a bytes-like object is required, not 'str'
<Greenlet at 0x7fda8555e048: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError

```

the strange thing is, the http requests work fine. I did not try the websocket route yet, as I first wanted to know if I'm doing something wrong or is this a bug?

**Comment by ChillingVan** [comment]
I also have same error. Is this because of we using python3?

**Comment by benma** [comment]
I also have this error, I am also using python3.

**Comment by oblalex** [comment]
I also confirm this with Python 3. Runs good with Python 2. I'll take a look.

**Comment by Xoerk** [comment]
Any update? I'm getting it on python3 also.

**Comment by arruda** [comment]
Maybe this would be a solution: https://www.mkyong.com/python/python-3-typeerror-str-does-not-support-the-buffer-interface/

**Comment by cemozerr** [comment]
I too have the same issue with TypeError on python 3.

**Comment by Alex-CodeLab** [comment]
the example seems to be incorrect, should be
 ```
        something = {'data':'test'}
        ws.send(message=json.dumps(something))
```

**Comment by BenePronomen** [comment]
Still having this issue. It's 2020 and it breaks in python 3 -_-
